# Config settings
title: Vikitravels slide testing
baseurl: "/jekyll-theme-vikitravels"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
